version: "3"

# service_name:
#   build: 
#     context: .
#     dockerfile: path/to/Dockerfile
#   restart: unless-stopped
#   labels:
#     com.mattermost.description: "Service Description"
#   depends_on:
#     - deps
#

# We will be making use of docker-compose overloads, so be sure to check the other compose files before reporting a missing field
# On local the containers will be built locally and tagged, able to be published.
# On prod the compose file will pull from the docker registry
services:

  server:
    restart: unless-stopped
    labels:
      com.mattermost.description: "Backend Service"
    depends_on: 
      - postgres
      
  postgres:
    image: postgres:latest
    restart: unless-stopped
    labels:
      com.mattermost.description: "Postgres Database"
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost_test # Initial schema name
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8065:8065
    labels:
      com.mattermost.description: "Adminer Database"
    depends_on: 
      - postgres